"""
System Field Mapping
Corrected and aligned strictly to the Excel field data provided.
- Removes redundant / synthetic fields
- Uses only Calculation Base values present in Excel
- Preserves Scale Base and Description exactly as defined
"""

SYSTEM_FIELD_MAPPING = {
    "ACTUAL_DATE": ("DATE", "Actual Execution Date"),
    "ACTUAL_DIST": ("DIST", "Actual Distance"),
    "ADD_AGR_PARTY": ("BP", "Additional Party"),
    "AIR_CD": ("AIR_CD", "IATA Airline Code"),
    "BILL_FROM_PARTY": ("BP", "Bill-from Party"),
    "BILL_TO_PARTY": ("BP", "Bill-to Party"),
    "CALC_DATE": ("DATE", "Calculation Date"),
    "CAL_BASE_FUCHS": ("C25WGT", "Calculation base for gross weight"),
    "CASH_ON_DLVRY": ("IND", "Cash on Delivery"),
    "CHRG_TYP": ("CHRTYP", "Charge Type"),
    "CHRG_WEIGHT": ("WEIGHT", "Chargeable Weight"),
    "CHRG_WEIGHT_NET": ("WEIGHT", "Chargeable Weight Based on Net Weight"),
    "COMMODITY_CODE": ("COM_CD", "Commodity Code"),
    "COMM_CODE_IATA": ("COM_CD", "IATA Commodity Code"),
    "COMM_CODE_MUL": ("COM_CD", "Commodity Code Multiple"),
    "CONDITION": ("CONDTN", "BRF+ Conditions"),
    "CONSOLID_TYPE": ("CONTYP", "Consolidation Type"),
    "CONTAINER_CNT": ("NUMBER", "No. of Containers in TEU"),
    "CONTINUOUS_MOVE": ("IND", "Continuous Move"),
    "CUSTOMS_VALUE": ("AMOUNT", "Customs Value"),
    "DANGEROUS_GOODS": ("IND", "Dangerous Goods"),
    "DAYS": ("DAYS", "No. of Days"),
    "DEF_ROUTE_ID": ("DROUTE", "Default Route ID"),
    "DELAY_TOT": ("DAYS", "Delay Days"),
    "DELIVER_HOLIDAY": ("IND", "Delivery Location Holiday"),
    "DESTINATION_CTY": ("CTY_CD", "Destination City"),
    "DESTLOC": ("LOC", "Destination Location"),
    "DESTLOC_CITY": ("CITY", "City of Destination Location"),
    "DESTLOC_CNTRY": ("CNTRY", "Destination Country"),
    "DESTLOC_PC": ("POSTCD", "Destination Location Postal Code"),
    "DESTLOC_PCRANGE": ("NUM_PC", "Destination Location Postal Code Range"),
    "DESTLOC_REG": ("REGION", "Destination Location Region"),
    "DESTLOC_UNLOCD": ("UNLOCD", "United Nations Code for Destination Location"),
    "DESTLOC_ZONE": ("TRZONE", "Transportation Zone of Destination Location"),
    "DEST_AIR_IATA": ("IATACD", "Airport Code of Destination"),
    "DEST_UNLOCD": ("UNLOCD", "United Nations Code for Destination Location"),
    "DIM_WEIGHT": ("WEIGHT", "Dimensional Weight"),
    "DURATION_GROSS": ("DUR", "Gross Duration"),
    "DURATION_NET": ("DUR", "Net Duration"),
    "EQUIP_GRP_CODE": ("EQPGRP", "Equipment Group"),
    "EQUIP_TYPE": ("EQPTYP", "Equipment Type"),
    "ESTD_DATE": ("DATE", "Estimated Event Date"),
    "EXEC_PARTY": ("BP", "Executing Party"),
    "FLIGHT_CODE": ("FLCODE", "Flight Code"),
    "FREIGHT_TERM": ("FRGHTR", "Freight Term"),
    "FRT_SRV_AGT": ("BP", "Freight Service Agent"),
    "FSC": ("AMOUNT", "Fuel Surcharge"),
    "GENERAL_NOTE": ("NOTE", "Notes"),
    "GIRTH": ("LENGTH", "Girth"),
    "GOODS_VALUE": ("AMOUNT", "Goods Value"),
    "GRACE_DAYS": ("DAYS", "Total Grace Period"),
    "GROSS_VOLUME": ("VOLUME", "Gross Volume"),
    "GROSS_WEIGHT": ("WEIGHT", "Gross Weight "),
    "HANDLING_CODE": ("HNDLCD", "Handling Code"),
    "HEIGHT": ("LENGTH", "Height"),
    "HOURS": ("DUR", "No. of Hours"),
    "IATANOTE": ("INOTE", "IATA Note"),
    "INCOLOC": ("LOC", "Incoterm Location"),
    "INCOTERMS": ("INCO", "Incoterm"),
    "INSURABLE_VALUE": ("AMOUNT", "Insurable Value"),
    "INSURANCE": ("IND", "Insurance Indicator"),
    "INTSTOP_SUBSTOP": ("NUMBER", "Number of Intermediate Stops Including Sub-stops"),
    "INVOICING_PARTY": ("BP", "Invoicing Party"),
    "ITEM_CATEGORY": ("ITMCAT", "Item Category"),
    "LANE": ("LANE", "Transportation Lane"),
    "LENGTH": ("LENGTH", "Length"),
    "MEANS_TRANSPORT": ("MEANTR", "Means of Transport"),
    "MODE_TRANSPORT": ("MODETR", "Transportation Mode"),
    "MULT_CHRG_TYP": ("CHRTYP", "Charge Type"),
    "NET_WEIGHT": ("WEIGHT", "Net Weight"),
    "NO_OF_AXLES": ("NUMBER", "Number of Axles"),
    "NO_OF_INT_STOPS": ("NUMBER", "Number of intermediate stops"),
    "NO_OF_RAILCARS": ("QTY", "Number of Resources for Rating"),
    "NUMBER_OF_STOPS": ("NUMBER", "Number of Stops"),
    "ORDERING_PARTY": ("BP", "Ordering Party"),
    "ORG_BY_ORDPARTY": ("IND", "Empty Provisioning or Return Organized by Ordering Party"),
    "ORG_EXT_ID": ("ORG", "Organization External ID"),
    "OUT_OF_GAUGE": ("IND", "Out-of-Gauge Indicator"),
    "OWNERSHIP_TYP": ("OWNTYP", "Ownership Type"),
    "PACKAGE_TYPE": ("PKGTYP", "Package Type"),
    "PAYER": ("PAYER", "Prepaid or Collect Charges"),
    "PERSON DAYS": ("NUMBER", "Person Days"),
    "PERSON DAYS(HR)": ("DUR", "Person Days in Hours"),
    "PER_DOCUMENT": ("NUMBER", "Per Document"),
    "PER_SHIPMENT": ("NUMBER", "Per Shipment"),
    "PICKUP_HOLIDAY": ("IND", "Pick-up Location Holiday"),
    "PLAND_DIST": ("DIST", "Distance"),
    "PLANNED_DATE": ("DATE", "Planned Event Date"),
    "POD_LOC": ("LOC", "Port of Discharge"),
    "POD_UNLOCD": ("UNLOCD", "United Nations Code for Port of Discharge"),
    "POL_LOC": ("LOC", "Port of Loading"),
    "POL_UNLOCD": ("UNLOCD", "United Nations Code for Port of Loading"),
    "PRD_FREIGHT_GRP": ("PRDGRP", "Product Freight Group"),
    "PRD_TRANSP_GRP": ("PRDTRN", "Product Transportation Group"),
    "PRODUCT_ID": ("PRD", "Product Identifier"),
    "QUANTITY_VAL": ("QTY", "Quantity"),
    "QUANTITY_VAL_2": ("QTY", "Alternative Quantity"),
    "SERVICE_CODE": ("SRVCD", "Service Type"),
    "SHIP_FROM_PARTY": ("BP", "Ship-from Party"),
    "SHIP_TO_PARTY": ("BP", "Ship-to Party"),
    "SLA": ("SLA", "Service Level Agreement"),
    "SLA_CARRIER": ("SLA_CA", "Service Level - Carrier"),
    "SOURCELOC": ("LOC", "Source Location"),
    "SOURCELOC_CITY": ("CITY", "City of Source Location"),
    "SOURCELOC_CNTRY": ("CNTRY", "Source Country"),
    "SOURCELOC_PC": ("POSTCD", "Source Location Postal Code"),
    "SOURCELOC_PCRNG": ("NUM_PC", "Source Location Postal Code Range"),
    "SOURCELOC_REG": ("REGION", "Source Location Region"),
    "SOURCELOC_ZONE": ("TRZONE", "Transportation Zone of Source Location"),
    "SOURCE_AIR_IATA": ("IATACD", "Airport Code of Departure"),
    "SOURCE_CITY": ("CTY_CD", "Source City Code"),
    "SRCLOC_UNLOCD": ("UNLOCD", "United Nations Code for Source Location"),
    "SRC_UNLOCD": ("UNLOCD", "United Nations Code for Source Location"),
    "STAGE_TYPE": ("STGTYP", "Stage Type"),
    "STOPS_SUBSTOPS": ("NUMBER", "Number of Stops Including Sub-stops"),
    "STR_LINE_DIST": ("DIST", "Aerial Distance"),
    "TIME_SPAN": ("TIME", "Time Span"),
    "TOT_CALC_WEIGHT": ("WEIGHT", "Total Calculation Weight"),
    "TRANS_PRIORITY": ("NUMBER", "Transportation Priority"),
    "TSP": ("BP", "Carrier"),
    "ULDRATETYPE": ("ULDRTT", "ULD Rate Type"),
    "VALUABLE_CARGO": ("IND", "Valuable Cargo Indicator"),
    "VEHICLE_GROS_WT": ("WEIGHT", "Vehicle Gross Weight Capacity"),
    "VEHICLE_GRO_VOL": ("VOLUME", "Vehicle Gross Volume Capacity"),
    "VEHICLE_TYPE": ("EQPTYP", "Vehicle Type"),
    "VOLUME_WT_FACT": ("VOLWTF", "Volumetric-Weight Factor"),
    "WEEKDAY": ("WKDAY", "Weekday"),
    "WIDTH": ("LENGTH", "Width"),
}
